### ISSUE TITLE
cannot edit existing talks (eg from Devoxx 2012)

### ISSUE THREAD

**Issue by jayv** [devoxx/cfp-speaker#26]
TypeError: Cannot read property 'tracks' of null
    at http://localhost:9000/scripts/speaker/SubmitProposal.js:79:54
    at http://localhost:9000/components/unstable-angular-complete/angular.js:10043:11
    at wrappedCallback (http://localhost:9000/components/unstable-angular-complete/angular.js:7509:59)
    at wrappedCallback (http://localhost:9000/components/unstable-angular-complete/angular.js:7509:59)
    at http://localhost:9000/components/unstable-angular-complete/angular.js:7582:26
    at Object.Scope.$eval (http://localhost:9000/components/unstable-angular-complete/angular.js:8926:28)
    at Object.Scope.$digest (http://localhost:9000/components/unstable-angular-complete/angular.js:8789:23)
    at Object.$delegate.**proto**.$digest (<anonymous>:833:31)
    at Object.Scope.$apply (http://localhost:9000/components/unstable-angular-complete/angular.js:9012:24)
    at Object.$delegate.**proto**.$apply (<anonymous>:844:30)

**Comment by stephanj** [comment]
The Devoxx'12 event doesn't have any tracks nor types defined in the admin, so its normal that these are null.

**Comment by jayv** [comment]
There's still an error after re-enabling the tracks and types, to be investigated

**Comment by jayv** [comment]
Server needs to send all events not only active, client needs to filter inactive events for new proposals
